// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: info_exchange_service.proto
#ifndef GRPC_info_5fexchange_5fservice_2eproto__INCLUDED
#define GRPC_info_5fexchange_5fservice_2eproto__INCLUDED

#include "info_exchange_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace exchangeservice {

class Exchanger final {
 public:
  static constexpr char const* service_full_name() {
    return "exchangeservice.Exchanger";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Request(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::exchangeservice::ReadResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::ReadResponse>> AsyncRequest(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::ReadResponse>>(AsyncRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::ReadResponse>> PrepareAsyncRequest(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::ReadResponse>>(PrepareAsyncRequestRaw(context, request, cq));
    }
    virtual ::grpc::Status Announce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::exchangeservice::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::Empty>> AsyncAnnounce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::Empty>>(AsyncAnnounceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::Empty>> PrepareAsyncAnnounce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::Empty>>(PrepareAsyncAnnounceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Request(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest* request, ::exchangeservice::ReadResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Request(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest* request, ::exchangeservice::ReadResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Announce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce* request, ::exchangeservice::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Announce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce* request, ::exchangeservice::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::ReadResponse>* AsyncRequestRaw(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::ReadResponse>* PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::Empty>* AsyncAnnounceRaw(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchangeservice::Empty>* PrepareAsyncAnnounceRaw(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Request(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::exchangeservice::ReadResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::ReadResponse>> AsyncRequest(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::ReadResponse>>(AsyncRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::ReadResponse>> PrepareAsyncRequest(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::ReadResponse>>(PrepareAsyncRequestRaw(context, request, cq));
    }
    ::grpc::Status Announce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::exchangeservice::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::Empty>> AsyncAnnounce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::Empty>>(AsyncAnnounceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::Empty>> PrepareAsyncAnnounce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchangeservice::Empty>>(PrepareAsyncAnnounceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Request(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest* request, ::exchangeservice::ReadResponse* response, std::function<void(::grpc::Status)>) override;
      void Request(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest* request, ::exchangeservice::ReadResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Announce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce* request, ::exchangeservice::Empty* response, std::function<void(::grpc::Status)>) override;
      void Announce(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce* request, ::exchangeservice::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::exchangeservice::ReadResponse>* AsyncRequestRaw(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchangeservice::ReadResponse>* PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::exchangeservice::ReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchangeservice::Empty>* AsyncAnnounceRaw(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchangeservice::Empty>* PrepareAsyncAnnounceRaw(::grpc::ClientContext* context, const ::exchangeservice::WriteAnnounce& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Request_;
    const ::grpc::internal::RpcMethod rpcmethod_Announce_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Request(::grpc::ServerContext* context, const ::exchangeservice::ReadRequest* request, ::exchangeservice::ReadResponse* response);
    virtual ::grpc::Status Announce(::grpc::ServerContext* context, const ::exchangeservice::WriteAnnounce* request, ::exchangeservice::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequest(::grpc::ServerContext* context, ::exchangeservice::ReadRequest* request, ::grpc::ServerAsyncResponseWriter< ::exchangeservice::ReadResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Announce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Announce() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Announce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Announce(::grpc::ServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnnounce(::grpc::ServerContext* context, ::exchangeservice::WriteAnnounce* request, ::grpc::ServerAsyncResponseWriter< ::exchangeservice::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Request<WithAsyncMethod_Announce<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Request() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::exchangeservice::ReadRequest, ::exchangeservice::ReadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchangeservice::ReadRequest* request, ::exchangeservice::ReadResponse* response) { return this->Request(context, request, response); }));}
    void SetMessageAllocatorFor_Request(
        ::grpc::MessageAllocator< ::exchangeservice::ReadRequest, ::exchangeservice::ReadResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchangeservice::ReadRequest, ::exchangeservice::ReadResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Request(
      ::grpc::CallbackServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Announce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Announce() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::exchangeservice::WriteAnnounce, ::exchangeservice::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchangeservice::WriteAnnounce* request, ::exchangeservice::Empty* response) { return this->Announce(context, request, response); }));}
    void SetMessageAllocatorFor_Announce(
        ::grpc::MessageAllocator< ::exchangeservice::WriteAnnounce, ::exchangeservice::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchangeservice::WriteAnnounce, ::exchangeservice::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Announce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Announce(::grpc::ServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Announce(
      ::grpc::CallbackServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Request<WithCallbackMethod_Announce<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Announce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Announce() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Announce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Announce(::grpc::ServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Announce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Announce() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Announce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Announce(::grpc::ServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnnounce(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Request() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Request(context, request, response); }));
    }
    ~WithRawCallbackMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Request(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Announce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Announce() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Announce(context, request, response); }));
    }
    ~WithRawCallbackMethod_Announce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Announce(::grpc::ServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Announce(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchangeservice::ReadRequest, ::exchangeservice::ReadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchangeservice::ReadRequest, ::exchangeservice::ReadResponse>* streamer) {
                       return this->StreamedRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::exchangeservice::ReadRequest* /*request*/, ::exchangeservice::ReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchangeservice::ReadRequest,::exchangeservice::ReadResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Announce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Announce() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchangeservice::WriteAnnounce, ::exchangeservice::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchangeservice::WriteAnnounce, ::exchangeservice::Empty>* streamer) {
                       return this->StreamedAnnounce(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Announce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Announce(::grpc::ServerContext* /*context*/, const ::exchangeservice::WriteAnnounce* /*request*/, ::exchangeservice::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAnnounce(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchangeservice::WriteAnnounce,::exchangeservice::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Request<WithStreamedUnaryMethod_Announce<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Request<WithStreamedUnaryMethod_Announce<Service > > StreamedService;
};

}  // namespace exchangeservice


#endif  // GRPC_info_5fexchange_5fservice_2eproto__INCLUDED
